# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170314_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
