# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170315_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
